services:
  - type: web
    name: omnitask-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: omnitask-db
          property: connectionString
      - key: SECRET_KEY
        sync: false

databases:
  - name: omnitask-db
    databaseName: omnitask
    user: omnitask
